// Code generated by goctl. DO NOT EDIT.

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tTowerDetailFieldNames          = builder.RawFieldNames(&TTowerDetail{})
	tTowerDetailRows                = strings.Join(tTowerDetailFieldNames, ",")
	tTowerDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(tTowerDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tTowerDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(tTowerDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tTowerDetailModel interface {
		Insert(ctx context.Context, data *TTowerDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TTowerDetail, error)
		Update(ctx context.Context, data *TTowerDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTTowerDetailModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TTowerDetail struct {
		Id          int64          `db:"id"`            // 主键ID
		SubitemId   int64          `db:"subitem_id"`    // 子项ID
		Name        string         `db:"name"`          // 基站名称
		Address     string         `db:"address"`       // 详细地区
		Image       sql.NullString `db:"image"`         // 基站图片，考虑是否支持展示多张
		CheckStatus sql.NullString `db:"check_status"`  // 检查状态
		CheckTime   sql.NullTime   `db:"check_time"`    // 检查时间
		CheckUserId sql.NullInt64  `db:"check_user_id"` // 检查人ID
		PrincipalId sql.NullInt64  `db:"principal_id"`  // 负责人ID
		PlanTime    sql.NullTime   `db:"plan_time"`     // 计划检查时间
		CreateTime  time.Time      `db:"create_time"`   // 创建时间
		UpdateTime  time.Time      `db:"update_time"`   // 更新时间
	}
)

func newTTowerDetailModel(conn sqlx.SqlConn) *defaultTTowerDetailModel {
	return &defaultTTowerDetailModel{
		conn:  conn,
		table: "`t_tower_detail`",
	}
}

func (m *defaultTTowerDetailModel) withSession(session sqlx.Session) *defaultTTowerDetailModel {
	return &defaultTTowerDetailModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`t_tower_detail`",
	}
}

func (m *defaultTTowerDetailModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTTowerDetailModel) FindOne(ctx context.Context, id int64) (*TTowerDetail, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTowerDetailRows, m.table)
	var resp TTowerDetail
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTowerDetailModel) Insert(ctx context.Context, data *TTowerDetail) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tTowerDetailRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SubitemId, data.Name, data.Address, data.Image, data.CheckStatus, data.CheckTime, data.CheckUserId, data.PrincipalId, data.PlanTime)
	return ret, err
}

func (m *defaultTTowerDetailModel) Update(ctx context.Context, data *TTowerDetail) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tTowerDetailRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.SubitemId, data.Name, data.Address, data.Image, data.CheckStatus, data.CheckTime, data.CheckUserId, data.PrincipalId, data.PlanTime, data.Id)
	return err
}

func (m *defaultTTowerDetailModel) tableName() string {
	return m.table
}
