// Code generated by goctl. DO NOT EDIT.

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userRolesRoleFieldNames          = builder.RawFieldNames(&UserRolesRole{})
	userRolesRoleRows                = strings.Join(userRolesRoleFieldNames, ",")
	userRolesRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(userRolesRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRolesRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(userRolesRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userRolesRoleModel interface {
		Insert(ctx context.Context, data *UserRolesRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserRolesRole, error)
		Update(ctx context.Context, data *UserRolesRole) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserRolesRoleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserRolesRole struct {
		Id     int64 `db:"id"`
		UserId int64 `db:"userId"`
		RoleId int64 `db:"roleId"`
	}
)

func newUserRolesRoleModel(conn sqlx.SqlConn) *defaultUserRolesRoleModel {
	return &defaultUserRolesRoleModel{
		conn:  conn,
		table: "`user_roles_role`",
	}
}

func (m *defaultUserRolesRoleModel) withSession(session sqlx.Session) *defaultUserRolesRoleModel {
	return &defaultUserRolesRoleModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`user_roles_role`",
	}
}

func (m *defaultUserRolesRoleModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserRolesRoleModel) FindOne(ctx context.Context, id int64) (*UserRolesRole, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRolesRoleRows, m.table)
	var resp UserRolesRole
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRolesRoleModel) Insert(ctx context.Context, data *UserRolesRole) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userRolesRoleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.RoleId)
	return ret, err
}

func (m *defaultUserRolesRoleModel) Update(ctx context.Context, data *UserRolesRole) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRolesRoleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.RoleId, data.Id)
	return err
}

func (m *defaultUserRolesRoleModel) tableName() string {
	return m.table
}
