// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	basestation "be/api/internal/handler/basestation"
	"be/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/base-station",
				Handler: basestation.CreateBaseStationHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/base-station/:id",
				Handler: basestation.UpdateBaseStationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/base-station/:id",
				Handler: basestation.GetBaseStationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/base-stations",
				Handler: basestation.ListBaseStationsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/base-station/:id",
				Handler: basestation.DeleteBaseStationHandler(serverCtx),
			},
		},
	)
}
